a = input('digite algo: ') 
print('o tipo primitivo desse valor é',type(a)) 
print('somente tem espasos?',a.isspace()) 
print('e um numero?',a.isnumeric()) 
print('tem letra?',a.isalpha()) 
print('e alfanumerico',a.isalnum()) 
print('ta em maiuscula?',a.isupper()) 
print('ta em minuscula?',a.islower())
print('esta capitalizada?',a.istitle())